### ISSUE TITLE
在Win下无法启动

### ISSUE THREAD

**Issue by tomluck2** [frost373/KitDB#2]
好像在Win下，路径会有错误，我的DB路径是：C:\my\cat\kitdb
```java
Caused by: top.thinkin.lightd.exception.KitDBException: STROE_ERROR
	at top.thinkin.lightd.db.DB.buildTransactionDB(DB.java:330) ~[store-0.1.2.jar:na]
	at top.thinkin.delayhunter.DelayhunterApplication.db(DelayhunterApplication.java:58) [classes/:na]
	at top.thinkin.delayhunter.DelayhunterApplication$$EnhancerBySpringCGLIB$$d3b2e4f8.CGLIB$db$0(<generated>) ~[classes/:na]
	at top.thinkin.delayhunter.DelayhunterApplication$$EnhancerBySpringCGLIB$$d3b2e4f8$$FastClassBySpringCGLIB$$8f5b371.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at top.thinkin.delayhunter.DelayhunterApplication$$EnhancerBySpringCGLIB$$d3b2e4f8.db(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	... 38 common frames omitted
aftdb2: ÎļþÃû¡¢Ŀ¼Ãû»ò¾í±êÓ﷨
	at org.rocksdb.TransactionDB.open(Native Method) ~[rocksdbjni-5.18.3.jar:na]
	at org.rocksdb.TransactionDB.open(TransactionDB.java:90) ~[rocksdbjni-5.18.3.jar:na]
	at top.thinkin.lightd.db.DB.buildTransactionDB(DB.java:324) ~[store-0.1.2.jar:na]
	... 49 common frames omitted

```

**Comment by frost373** [comment]
盘符开头的windows路径支持不好。`C:\\my\\cat\\kitdb` 这样即可解决问题

**Comment by tomluck2** [comment]
已经启动成功啦！
